### ISSUE TITLE
Broken package

### ISSUE THREAD

**Issue by WHenderson** [nlepage/typedoc-plugin-resolve-crossmodule-references#1]
I think the package sent to npm is broken. 

```bash
Error: The plugin typedoc-plugin-resolve-crossmodule-references could not be loaded.
Error: Error: Cannot find module '.../node_modules/typedoc-plugin-resolve-crossmodule-references/dist'. Please verify that the package.json has a valid "main" entry
 ```

Whe you look in `node_modules/typedoc-plugin-resolve-crossmodule-references` there is no `dist` folder.

I found this plugin whilst reviewing [Cross-package references in monorepository not working #1835](https://github.com/TypeStrong/typedoc/issues/1835)

**Comment by nlepage** [comment]
Sorry about this, I'll have a look tomorrow and keep you updated.

**Comment by nlepage** [comment]
Hi @WHenderson 
Turns out there is a `dist` folder in the release.
I think somehow you may have an error in your import path which begins with 3 dots: `'.../node_modules/`
Closing this, will reopen if necessary.

**Comment by WHenderson** [comment]
I do apologize, it seems that I initially installed using this:

```bash
> pnpm add -w --save-dev nlepage/typedoc-plugin-resolve-crossmodule-references
```

Which appears to install the actual source via github although the package.json is updated without any mention of github or nlepage.

I should have been using:

```bash
> pnpm add -w --save-dev typedoc-plugin-resolve-crossmodule-references
```

which uses the compiled npm package.

The module is loading now without error.

**Comment by nlepage** [comment]
No problem.
