### ISSUE TITLE
Generic type defaults dont seem to be mapped

### ISSUE THREAD

**Issue by cm226** [nlepage/typedoc-plugin-resolve-crossmodule-references#10]
came across this issue while using this plugin, 

If I have:
`export function someFunction<T extends ISomething= ISomething>`

where ISomething is from a different module I get:

`warning ISomething is referenced by someFunction but not included in the documentation`

It looks like its only the default value thats not mapped to the new module, because this definition:

`export function someFunction<T extends ISomething>`

compiles ok.

**Comment by nlepage** [comment]
Hi @cm226, good catch, thanks for reporting the issue.
Just published v0.3.1 to fix this, let me know if this OK for you.

**Comment by cm226** [comment]
@nlepage Yep confirm that new version fixes the issue, thanks!
