### ISSUE TITLE
Cross-module references with `@link` are not recognized

### ISSUE THREAD

**Issue by Tschakki** [nlepage/typedoc-plugin-resolve-crossmodule-references#15]
### Description
As the title says, I think there is a bug that `@link` cross-modue references are not recognized by the plugin.

### Example:
I try to reference a class in another module like this:
```
@see {@link LiskValidator}
@see {@link Lisk_Validator.LiskValidator}
@see {@link LiskValidationError}
@see {@link Lisk_Validator.LiskValidationError}
```
As I am new to TypeDoc, it might also be that I am referencing incorrectly, so I tried a few different ways, but none of the above links work.

The rendered result looks like this: 
<img width="506" alt="image" src="https://user-images.githubusercontent.com/1993505/209931018-84b4c8a6-dba9-4805-aef0-565403a9eccd.png">

As you can see,under `Returns` the link it recognized successfully for `LiskValidationError`, but under `See` the link is not recognized.

Here is the link to the example:
https://liskhq.github.io/lisk-docs/lisk-sdk/v6/references/typedoc/functions/_liskhq_lisk_transactions.validateTransaction.html

**Comment by nlepage** [comment]
Thanks for opening the issue. I'll try to look at this shortly.

**Comment by nlepage** [comment]
Judging from [Typedoc's documentation](https://typedoc.org/tags/see/) the syntax seems correct, so that's probably a case we haven't already managed in the plugin.

**Comment by Gerrit0** [comment]
This plugin shouldn't have to do anything for links. According to TypeDoc, this link is invalid. `{@link @liskhq/lisk-validator!LiskValidationError}` should work. The [Declaration references](https://typedoc.org/guides/declaration-references/) docs describes how links are resolved.

**Comment by Tschakki** [comment]
Thanks @Gerrit0 , you are right, my references were not correct. The example that you shared works well for me, thanks a lot!
