### ISSUE TITLE
findSymbolSourceFile reliant on source maps.. which don't seem to be present

### ISSUE THREAD

**Issue by WHenderson** [nlepage/typedoc-plugin-resolve-crossmodule-references#3]
```const srcMapConverter = fromSource(declSrcFile.text) ?? fromMapFileSource(declSrcFile.text, srcDirPath)```
returns null for me. It seems that source maps are not being generated for me.

Either way, I'm not sure they are necessary.
I replaced the logic with:

```js
        const declSrcFile = declaration.getSourceFile();
        const declSrcFileName = declSrcFile.fileName;
        const srcFile = project.files.find(({ fullFileName }) => fullFileName === declSrcFileName);
        if (!srcFile)
            continue;
        return srcFile;
```

and it seems to be working fine. 

I'm probably missing something important but just wanted to get something working.

**Comment by nlepage** [comment]
Hi @WHenderson 
You can find an example of setup to make this plugin work in the [test packages](https://github.com/nlepage/typedoc-plugin-resolve-crossmodule-references/tree/main/test).
Here's how to run it:
```sh
# clone the repository then:
cd typedoc-plugin-resolve-crossmodule-references
yarn # install deps
yarn build # build the plugin
yarn test:build # build the test projects
cd test
yarn typedoc --out ../docs # regenerate the documentation
```
If this isn't of any help, maybe provide an example of your setup?
Thanks in advance for your help.

**Comment by WHenderson** [comment]
I've sent a pull request your way.
I still don't have a good way to show the problem of when source maps don't exist, but they definitely don't for my main repo (which isn't yet public :-/).

**Comment by nlepage** [comment]
New release [v0.2.0](https://github.com/nlepage/typedoc-plugin-resolve-crossmodule-references/releases/tag/v0.2.0) doesn't rely on source maps anymore.
