### ISSUE TITLE
link doesn't work when implementing an interface

### ISSUE THREAD

**Issue by imranbarbhuiya** [nlepage/typedoc-plugin-resolve-crossmodule-references#7]
The plugin isn't working for `implement`. Like I'm implementing an interface from another package of the monorepo and it's breaking. repro: https://github.com/imranbarbhuiya/TagScript/pull/53

line: https://github.com/imranbarbhuiya/TagScript/blob/b77fe5e98f018f1ffe8925ad840088a012bec903/packages/tagscript-plugin-discord/src/lib/Parsers/Cooldown.ts#L24

**Comment by nlepage** [comment]
Just published a new release v0.2.1 to fix this, let me know it is OK for you.

**Comment by imranbarbhuiya** [comment]
Yeah, It worked thanks.
